[package]
name = "fire-emblem-rs"
version = "0.1.0"
authors = ["Luc Tielen <luc.tielen@gmail.com>"]

[dependencies]
gtk = "^0.2.0"
gdk = "^0.6.0"
gdk-pixbuf = "0.2.0"
relm = "^0.10.1"
relm-derive = "^0.10.0"
relm-attributes = "^0.10.0"
cairo-rs = "^0.2.0"
futures = "0.1.16"
futures-glib = "0.2.1"
